services:
  frontend:
    env_file:
      - .env
    build:
      dockerfile: ./docker/Dockerfile-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"

  backend:
    env_file:
      - .env
    build:
      dockerfile: ./docker/Dockerfile-backend
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    depends_on:
      - db

  db:
    image: mysql:8.3
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./db:/var/lib/mysql"
